---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - jmbayu.nfs
    - jmbayu.packer_debian

  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
        state: installed